- name: Install packages
  package:
    name: "{{ packages }}"
    state: present
- name: Copy public ssh key
  copy:
    dest: "/root/.ssh/authorized_keys"
    content: "{{ ssh_public_key }}"
- name: ensure client NTP config is setup
  copy: src=files/ntp.conf dest=/etc/ntp/ntp.conf
  notify: 
    - restart ntp
  when: ansible_facts['hostname'] != "dns1.esxi.com"